### ISSUE TITLE
[BUG] Not working with new DLC after update

### ISSUE THREAD

**Issue by Pegaiur** [Squirrelies/RE2REmakeSRT#13]
**Computer Information:**

* OS: Windows 10 Version 1809
* Program Version: 1.0.6.1&1.1.8.5
* Game Version: 1.02 (assumed, with new free DLC)

**Describe the bug**
When the game is running, the program alerts 'unknow version of RE2. may encounter issues'. No longer showing any in-game information.

**Comment by Squirrelies** [comment]
Yeah... looks like the pointers changed. I'll have to find the new base addresses for this version. May take a day or so.

**Comment by Squirrelies** [comment]
Fixed with 1.2.0.0.
