### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by myfatesky** [Squirrelies/RE2REmakeSRT#14]
**Computer Information:**
 - OS: Windows 10 Version 1809
 - Program Version : 1.2.0.0
 - Game Version : 1.0.2?(Latest game version)

**Describe the bug**
Because my English is not good, I used machine translation.
Please bear with me ：）
After the game is upgraded, the software does not work properly.
Even if the software is already the latest version
By the way, the previous old version (1.1.8.0 + previous game version before dlc updated ) could run normally.
The specific situation is:
The software works fine, but can not display any data.

**Screenshots**
![bug report](https://user-images.githubusercontent.com/47721525/52917837-dcf1fc00-332a-11e9-9fd2-7d4aedcd7813.png)
![bug report 2](https://user-images.githubusercontent.com/47721525/52917975-50483d80-332c-11e9-80dd-7e94d86043f6.jpg)
![bug report 3](https://user-images.githubusercontent.com/47721525/52918716-26474900-3335-11e9-848e-31725080b787.jpg)

**Comment by Squirrelies** [comment]
Did you restart the game without restart the SRT? Does it always have this problem?

**Comment by myfatesky** [comment]
yes...
always shows the same problem, no matter how I tried，
I still couldn't make it run.
It displayed nothing. XD
I also did what you said like:
    ----1,launch the game
    ----2,then launch the SRT
    ----3,re-launch the game

**Comment by Squirrelies** [comment]
Does this issue still exist with 1.3.0.0 and the latest version of the game?

**Comment by myfatesky** [comment]
after I reinstalled my windows OS,
all the problems was solved.
I am not sure but I guess maybe the update bug of win10 caused all things.
anyway, thx for your time

by the way, Before the problem occurred, The OS version I have used was Win10 1709.

**Comment by Squirrelies** [comment]
Thanks for the info. I'll mark this as closed but keep note that there may be an unresolved issue in Windows 10 1709.
