### ISSUE TITLE
[BUG] Possible memory override making G4 invincible

### ISSUE THREAD

**Issue by jorgebonafe** [Squirrelies/RE2REmakeSRT#15]
**Computer Information:**
 - OS: Windows 10 Version 1803
 - Program Version: 1.2.0.0
 - Game Version: Not sure how to check, it's the DLC release version from february 15

**Describe the bug**
Ok, so I had this problem, on Claire Hardcore, and I don't know if it's related to this tool or not. As I reached the final boss, G4 on the train, his health numbers were huge, like over a million or so. I discharged the whole minigun on him, and then 60 pistol bullets, and like 5 fire rounds, and his health reached about 99.1%. Then my bullets ran out, then the time ran out. I killed this guy on hardcore twice before, and I know it's not a case of me being an awful shot.

I googled this, and the only other instance that I could find of G4 being unkillable was this thread on steam:

https://steamcommunity.com/app/883710/discussions/1/1779388024847702909/

It seems this guy was also using a health display. He didn't specify which one, but at least it seems plausible this could be an issue with this tool, so just in case I thought I'd post this here. I know this tool needs to read the game's memory to get health values and etc, so maybe there is a problem somewhere that is overriding the boss's health with an insane number.

**Steps to Reproduce**
I was playing on Hardcore Claire A, running the tool, and the problem happened when I reached G4. I have linked the save file bellow if it helps. I apologise for the save location, I was trying for S+, so I didn't save before G4, I saved before G3.

https://www.dropbox.com/s/92h5di78va9in6c/data013Slot.bin?dl=0

**Comment by Squirrelies** [comment]
His HP is actually ~3 million. He is scripted to die after a certain number of eye balls are killed. His HP is set that way to prevent people from just ignoring the mechanic of the fight.
