### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Draskil** [Squirrelies/RE2REmakeSRT#16]
**Computer Information:**
 - OS: [e.g. Windows 10 Version 1809 (Start + 'winver' to find out)]
 - Program Version [e.g. 1.0.2]
 - Pirated version :(

**Describe the bug**
The tool does not work and occasional error message shows 

**Steps to Reproduce**
1. Opened SRT
2. Opened Pirated ver of RE2
3. Then this error shows up and tool won't work.

**Expected behavior**
Maybe this only happens to the pirated version of the game. 

**Screenshots**
ERROR POP UPhttp://prntscr.com/mp2wi3

**Additional context**

**Comment by Squirrelies** [comment]
I'll look into this, only because it may affect non-pirated versions.

**Comment by fablacky** [comment]
It seems to be specific to pirated versions only. It never occurred on a original copy of the game in almost a week. I tried downloading a pirated version of the game and it showed up after a couple boots of the game.

**Comment by Squirrelies** [comment]
Non-pirated copies are unsupported.
