### ISSUE TITLE
Crashes after a while

### ISSUE THREAD

**Issue by ShockViper** [Squirrelies/RE2REmakeSRT#17]
Computer Information:

    OS: Windows 7 Version 6.1 Build 7601 SP 1
    Program Version 1.3.1
    Game Version latest patch

Describe the bug A clear and concise description of what the bug is.
After a while program crashes and stops displaying ingame time and enemy HP. Health and inventory continue to work just fine.

Screenshot:
![error srt](https://user-images.githubusercontent.com/44064447/53298669-86585680-3831-11e9-868d-87f2dcf6ae49.png)

Details from the error:

Exception Text
************** Exception Text **************
System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Single x, Single y, Single width, Single height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, RectangleF rect)
   at RE2REmakeSRT.MainUI.DrawProgressBar(PaintEventArgs e, Brush bgBrush, Brush foreBrush, Single x, Single y, Single width, Single height, Single value, Single maximum)
   at RE2REmakeSRT.MainUI.statisticsPanel_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

RE2REmakeSRT
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
    CodeBase: file:///E:/livesplit/srt/RE2REmakeSRT-1310-Beta-Signed-Release/RE2REmakeSRT.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

ProcessMemory
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///E:/livesplit/srt/RE2REmakeSRT-1310-Beta-Signed-Release/ProcessMemory.DLL

netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll

DoubleBuffered
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///E:/livesplit/srt/RE2REmakeSRT-1310-Beta-Signed-Release/DoubleBuffered.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

**Comment by Squirrelies** [comment]
Appears to be an issue where the DrawProgressBar method is drawing out of bounds of the panel area. I'll work on reproducing this so I can fix and test.

**Comment by Squirrelies** [comment]
I was able to reproduce the error. It can happen at any time. It is as I expected. the drawing rectangle had a width WAY out of range. The enemy info had a CurrentHP far in excess of MaximumHP. I am not sure if I can filter it out via the pointer code but I know I can filter on CurrentHP > MaximumHP. I'll release a fix soon.

**Comment by Squirrelies** [comment]
I believe I fixed this in 1.3.2.0. Closing. Thanks!
