### ISSUE TITLE
[BUG] Unable to play on full screen mode.

### ISSUE THREAD

**Issue by fablacky** [Squirrelies/RE2REmakeSRT#18]
**Computer Information:**
 - OS: W7 7601 SP1
 - Program Version 1.3.2.0
 - Game Version 1.0.3

**Describe the bug**
I'm able to play and have the tool in the same screen only if I'm in windowed mode (and resized enough so that both program windows can be put side to side), otherwise it will just show a black screen

**Steps to Reproduce**
Run RE2REmakeSRT
Enable "Always on top" option
Run RE2
Black screen (although you can hear RE2 sounds effects)
I'm able to see the game only by ALT+TAB, close RE2REmakeSRT and ALT+TAB again

**Comment by emjay101** [comment]
get a second monitor or use windowed fullscreen -_-

**Comment by fablacky** [comment]
That's what I've been doing, I was just wondering if it would be possible to make it work fullscreen on a single monitor

**Comment by emjay101** [comment]
Bordlerless window in re graphics setting +your monitors native resolution should do the trick.

**Comment by Squirrelies** [comment]
I am working on a DirectX Overlay mode that should work better than Borderless + Always on Top but its still being developed.

**Comment by fablacky** [comment]
> Bordlerless window in re graphics setting +your monitors native resolution should do the trick.
The main problem with either this or windowed mode is the pointer. It will appear on the SRT if I move the visual too much (le'ts say I'm aiming in either corner of the visual) and if I fire my weapon the tool will catch the mouseclick event instead of re2, although I realize it may be inevitable given the Always on top option being enabled.

> I am working on a DirectX Overlay mode that should work better than Borderless + Always on Top but its still being developed.

Excellent, that's all I wanted to know. Thank you so much

**Comment by angelstrong** [comment]
The chronometer does not run me in the Pirate Game

**Comment by Squirrelies** [comment]
@fablacky DirectX Overlay is now live but there is another bug where it does not work in DX11 Full screen mode. It does however work in DX12 full screen, DX12 borderless window and DX11 borderless window modes.
@angelstrong Non-pirated copies are unsupported.
